### ISSUE TITLE
Problem with performance!

### ISSUE THREAD

**Issue by thearabbit** [adam-hanna/goal-seek#9]
By example in issue : [Could I set Optional for maxIterations?](https://github.com/adam-hanna/goal-seek/issues/8).
I tried the big loan amount `~00,000,000.00`, It take a long time `> 30 m` for running the schedule.
But It is very quickly on `Goal-Seek Excel Method`.
Should your help me.

**Comment by adam-hanna** [comment]
Yeah, it's not going to be as performant as excel. The best way to improve performance is to choose a first guess that is as close to the real value as possible

**Comment by thearabbit** [comment]
thanks for your reply.
Now I tried with the  new `Interpolation/Forecast Method`, It work fine (the same result) and good performance.
👍
